### ISSUE TITLE
Deine Style for lists items

### ISSUE THREAD

**Issue by CestDiego** [CestDiego/just_right#12]
this is hurribluuu
[![alt](https://i.imgur.com/zKN3Hl9.png)](https://i.imgur.com/zKN3Hl9.png)

Fix:
Resources:
- http://www.macworld.com/article/1048296/januarycreate.html
- http://techforluddites.com/replacing-list-bullets-with-images-using-css/

**Comment by ppold** [comment]
Closed by 7c60dde.

**Comment by CestDiego** [comment]
great thx <3
